secrets:
  db_password:
    file: secrets/postgres_password.txt
  db_user:
    file: secrets/postgres_user.txt
  db_name:
    file: secrets/postgres_db.txt
  db_conn_url:
    file: secrets/postgres_db_conn.txt

services:
  database:
    image: postgres
    restart: always
    secrets:
      - db_password
      - db_user
      - db_name
      - db_conn_url
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh", "-c", "pg_isready -d $(cat /run/secrets/db_conn_url)"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    secrets:
      - db_conn_url
    ports:
      - 1337:1337
    develop:
      watch:
        - action: rebuild
          path: ./src
    depends_on:
      database:
        condition: service_healthy
